apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/__CLUSTER__/services
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  decryption:
    provider: sops
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: env-vars
    - kind: Secret
      name: env-secret-vars