apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: __TENANT__

components:
  - ../../../../components/feature-flags
  - ../../../../components/kubelet
resources:
- ./dist.yaml
- ./services
- ./users

patches:
- path: ../../../../base/global-overrides.yaml
  target:
    kind: HelmRelease