apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 15m0s
  dependsOn:
  - name: infrastructure
  - name: services
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/__CLUSTER__/tenants
  prune: true
  wait: true
  force: true
  timeout: 5m0s